version: '3.8'

services:
  landing:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        ENV_FILE: envlocal
    image: pmois/moneybag:moneybag-portal-next
    ports:
      - "7009:7009"
    environment:
      NODE_ENV: production
      FORCE_COLOR: 2
    restart: unless-stopped


    