version: '3.8'

services:
  landing:
    build:
      context: .
      dockerfile: Dockerfile
    image: moneybag-web:latest
    ports:
      - "7009:7009"
    environment:
      NODE_ENV: production
    restart: unless-stopped
    


    